### ISSUE TITLE
Conda-forge package tracking list

### ISSUE THREAD

**Issue by matthewfeickert** [hep-packaging-coordination/packaging-hep-simulation-stack#1]
## Initial goal targets

* [ ] [mg5amcnlo](https://github.com/mg5amcnlo/mg5amcnlo/)
   - https://github.com/mg5amcnlo/mg5amcnlo/issues/156
   - https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/3
* [x] PYTHIA8: (https://github.com/conda-forge/pythia8-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/pythia8.svg)](https://anaconda.org/conda-forge/pythia8)
* [x] LHAPDF: (https://github.com/conda-forge/lhapdf-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/lhapdf.svg)](https://anaconda.org/conda-forge/lhapdf)
* [x] HepMC2: (https://github.com/conda-forge/hepmc2-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/hepmc2.svg)](https://anaconda.org/conda-forge/hepmc2)
* [x] HepMC3: (https://github.com/conda-forge/hepmc3-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/hepmc3.svg)](https://anaconda.org/conda-forge/hepmc3)
* [x] `fastjet`: (https://github.com/conda-forge/fastjet-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/fastjet.svg)](https://anaconda.org/conda-forge/fastjet)
> [!WARNING]
> `fastjet` builds are currently broken

* [x] [SISCone](https://gitlab.com/fastjet/siscone): (https://github.com/conda-forge/siscone-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/siscone.svg)](https://anaconda.org/conda-forge/siscone)
* [x] [FastJet](https://gitlab.com/fastjet/fastjet) (`fastjet-cxx`): (https://github.com/conda-forge/fastjet-cxx-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/fastjet-cxx.svg)](https://anaconda.org/conda-forge/fastjet-cxx)
* [x] [fastjet-contrib](https://fastjet.hepforge.org/contrib/): (https://github.com/conda-forge/fastjet-contrib-feedstock)
   - `fastjet-contrib`: [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/fastjet-contrib.svg)](https://anaconda.org/conda-forge/fastjet-contrib)
   - `fastjet-contrib-static`: [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/fastjet-contrib-static.svg)](https://anaconda.org/conda-forge/fastjet-contrib-static)

* [x] YODA: (https://github.com/conda-forge/yoda-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/yoda.svg)](https://anaconda.org/conda-forge/yoda)
> [!WARNING]
> Yoda builds are currently broken
* [x] ROOT: (https://github.com/conda-forge/root-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/root.svg)](https://anaconda.org/conda-forge/root)
* [x] Delphes: (https://github.com/conda-forge/delphes-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/delphes.svg)](https://anaconda.org/conda-forge/delphes) 
> [!WARNING]
> Delphes builds are currently broken
   - [x] Waiting for merge of https://github.com/conda-forge/staged-recipes/pull/27903
* [x] Geant4 (https://github.com/conda-forge/geant4-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/geant4.svg)](https://anaconda.org/conda-forge/geant4)

## Bonus goal targets

- [x] [Sherpa](https://gitlab.com/sherpa-team/sherpa) (https://github.com/conda-forge/sherpa-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/sherpa.svg)](https://anaconda.org/conda-forge/sherpa)
- [ ] [Powheg](https://powhegbox.mib.infn.it/#Downloads) (Only on SVN, so will be annoying to get tarballs)
   - Amazing: [`conda-build` can handle SVN urls as `source`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-from-svn).
- [ ] [HERWIG7](https://herwig.hepforge.org/tutorials/index.html#manual-installation)
- [ ] [Rivet](https://rivet.hepforge.org/downloads/)
- [ ] [GoSam](https://github.com/gudrunhe/gosam)
   - c.f. https://github.com/gudrunhe/gosam/issues/10#issuecomment-2462890635
- [ ] [Golem95](https://golem.hepforge.org/) (Hepforge tarball links are broken)
   - c.f. https://github.com/gudrunhe/gosam-contrib/issues/1
- [ ] [SAMURAI](https://samurai.hepforge.org/) (Hepforge tarball links are broken)
- [x] [QCDloop](https://github.com/scarrazza/qcdloop) (C++ version) (https://github.com/conda-forge/qcdloop-feedstock)
   - [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/qcdloop.svg)](https://anaconda.org/conda-forge/qcdloop)
- [ ] [PEPPER](https://gitlab.com/spice-mc/pepper) (would be an interesting candidate given GPU support)

**Comment by kratsg** [comment]
Other packages:
- Sherpa
- Powheg

**edit by @matthewfeickert:** Added above.

**Comment by matthewfeickert** [comment]
For building guidance on some of the generators, c.f. an earlier attempt at https://github.com/matthewfeickert/hep-simulation-stack

**Comment by matthewfeickert** [comment]
Build issues with modern Sherpa: https://gitlab.com/sherpa-team/sherpa/-/issues/602

**Comment by matthewfeickert** [comment]
Build issues (on conda-forge only) with Sherpa v2 here: https://github.com/conda-forge/staged-recipes/pull/28084

**Comment by matthewfeickert** [comment]
RooUnfold: Issue https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/5

(Also this repo should probably get renamed to something more general than "simulation stack")

**Comment by matthewfeickert** [comment]
Rivent: Issue https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/7
